### ISSUE TITLE
Default amount of gas is too small

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/nearlib#176]
The default amount of gas for function call is too small and developers often have to set this value manually. Since the unused gas will be returned it seems reasonable to pass in maximum allowed amount of gas for function calls.

**Comment by amgando** [comment]
**problem**

unable to complete [cross contract call tutorial](https://docs.nearprotocol.com/docs/tutorials/how-to-write-contracts-that-talk-to-each-other) due to upper limit on size of number that can be passed to a smart contract function call via `nearlib`

**detail**

recently @evgenykuzyakov [submitted to Slack `#general`](https://studio.nearprotocol.com/?f=121ay3d5g&quickstart) (see line `72` in `main.js`)  an example of increasing the amount of gas submitted to 9.9 NEAR when invoking a function call.  This seems to work find as a passthrough value since no checks are made in `nearlib` on the size of the number, it goes directly to `nearcore`.  The example works fine.

But since we're using `BN.js` in `nearlib` we're limited by this assertion:
[`assert(number < 0x20000000000000); // 2 ^ 53 (unsafe)`](https://github.com/indutny/bn.js/blob/aff3260968b30a51fcb449037f040ec3919c2582/lib/bn.js#L128) 

This line limits us to 
`9007199254740991`, which is much smaller than 
`99000000000000000000` suggested by the working example linked above.

Transaction [6fci1ciicWLM7JFcdZVDWaDXtJpzMScvvA6GmEuLPTZc](https://explorer.nearprotocol.com/transactions/6fci1ciicWLM7JFcdZVDWaDXtJpzMScvvA6GmEuLPTZc) failed. **Exceeded the prepaid gas**

**reproduction**

- open https://studio.nearprotocol.com/?f=7cd5vk11b
- run the test
- note error [Transaction failed](http://explorer.nearprotocol.com/transactions/DipgHNoRZ38RqqcF6pRbU7AbvGjmCVjTM3hvM3CErdmf). **Exceeded the prepaid gas.**

- edit the value in `src/test.js` line `36` by incrementing the gas passed as an argument to `contract.calculate()` from 
900719925474099**1** to 
900719925474099**2**
- run the test
- note error `Error: Assertion failed` coming from the assertion on [this line](https://github.com/indutny/bn.js/blob/aff3260968b30a51fcb449037f040ec3919c2582/lib/bn.js#L128) in BN.js (one of our `nearlib` dependencies, line `3204`)

```text
Error: Assertion failed
    at assert (https://cdn.jsdelivr.net/npm/nearlib@0.20.0/dist/nearlib.js:3082:21)
    at BN._initNumber (https://cdn.jsdelivr.net/npm/nearlib@0.20.0/dist/nearlib.js:3204:7)
```

**Comment by kcole16** [comment]
@bowenwang1996 Is the max amount of gas allowed for function calls a constant?

**Comment by bowenwang1996** [comment]
yes

**Comment by vgrichina** [comment]
@amgando 
> But since we're using BN.js in nearlib we're limited by this assertion:
assert(number < 0x20000000000000); // 2 ^ 53 (unsafe)

we aren't, just need to pass number as decimal string, i.e. `new BN("99000000000000000000")`

**Comment by amgando** [comment]
> we aren't, just need to pass number as decimal string, i.e. `new BN("99000000000000000000")`

@vgrichina oh jeez 🤦‍♂

**Comment by amgando** [comment]
@vgrichina -- just thinking about this again now.  `BN` is available in a JS context but this number is being passed to `ContractPromise.create` in an AssemblyScript context.  unfortunately i'll have to revisit this more carefully after retracing my steps since I couldn't easily reproduce the problem I experienced before
